// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrewrpbzulimhofvivlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyZXdycGJ6dWxpbWhvZnZpdmxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTMzODIsImV4cCI6MjA2NjMyOTM4Mn0.5yAtsVYRnYzh6i4I7Er10lLKnYd7cmdgBwLcm5sIaqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);