// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdocprtegtttvwhdkvlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkb2NwcnRlZ3R0dHZ3aGRrdmxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDgyOTUsImV4cCI6MjA2NTEyNDI5NX0.APJSYMCO1CNW6Vn6p_Cq2JswOzBnW8jpCRRHxKg3Zok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);